require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe AbTestsController do

  # This should return the minimal set of attributes required to create a valid
  # AbTest. As you add validations to AbTest, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { {  } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # AbTestsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all ab_tests as @ab_tests" do
      ab_test = AbTest.create! valid_attributes
      get :index, {}, valid_session
      assigns(:ab_tests).should eq([ab_test])
    end
  end

  describe "GET show" do
    it "assigns the requested ab_test as @ab_test" do
      ab_test = AbTest.create! valid_attributes
      get :show, {:id => ab_test.to_param}, valid_session
      assigns(:ab_test).should eq(ab_test)
    end
  end

  describe "GET new" do
    it "assigns a new ab_test as @ab_test" do
      get :new, {}, valid_session
      assigns(:ab_test).should be_a_new(AbTest)
    end
  end

  describe "GET edit" do
    it "assigns the requested ab_test as @ab_test" do
      ab_test = AbTest.create! valid_attributes
      get :edit, {:id => ab_test.to_param}, valid_session
      assigns(:ab_test).should eq(ab_test)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new AbTest" do
        expect {
          post :create, {:ab_test => valid_attributes}, valid_session
        }.to change(AbTest, :count).by(1)
      end

      it "assigns a newly created ab_test as @ab_test" do
        post :create, {:ab_test => valid_attributes}, valid_session
        assigns(:ab_test).should be_a(AbTest)
        assigns(:ab_test).should be_persisted
      end

      it "redirects to the created ab_test" do
        post :create, {:ab_test => valid_attributes}, valid_session
        response.should redirect_to(AbTest.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved ab_test as @ab_test" do
        # Trigger the behavior that occurs when invalid params are submitted
        AbTest.any_instance.stub(:save).and_return(false)
        post :create, {:ab_test => {  }}, valid_session
        assigns(:ab_test).should be_a_new(AbTest)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        AbTest.any_instance.stub(:save).and_return(false)
        post :create, {:ab_test => {  }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested ab_test" do
        ab_test = AbTest.create! valid_attributes
        # Assuming there are no other ab_tests in the database, this
        # specifies that the AbTest created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        AbTest.any_instance.should_receive(:update_attributes).with({ "these" => "params" })
        put :update, {:id => ab_test.to_param, :ab_test => { "these" => "params" }}, valid_session
      end

      it "assigns the requested ab_test as @ab_test" do
        ab_test = AbTest.create! valid_attributes
        put :update, {:id => ab_test.to_param, :ab_test => valid_attributes}, valid_session
        assigns(:ab_test).should eq(ab_test)
      end

      it "redirects to the ab_test" do
        ab_test = AbTest.create! valid_attributes
        put :update, {:id => ab_test.to_param, :ab_test => valid_attributes}, valid_session
        response.should redirect_to(ab_test)
      end
    end

    describe "with invalid params" do
      it "assigns the ab_test as @ab_test" do
        ab_test = AbTest.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        AbTest.any_instance.stub(:save).and_return(false)
        put :update, {:id => ab_test.to_param, :ab_test => {  }}, valid_session
        assigns(:ab_test).should eq(ab_test)
      end

      it "re-renders the 'edit' template" do
        ab_test = AbTest.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        AbTest.any_instance.stub(:save).and_return(false)
        put :update, {:id => ab_test.to_param, :ab_test => {  }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested ab_test" do
      ab_test = AbTest.create! valid_attributes
      expect {
        delete :destroy, {:id => ab_test.to_param}, valid_session
      }.to change(AbTest, :count).by(-1)
    end

    it "redirects to the ab_tests list" do
      ab_test = AbTest.create! valid_attributes
      delete :destroy, {:id => ab_test.to_param}, valid_session
      response.should redirect_to(ab_tests_url)
    end
  end

end
