require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe YesOrNoTestsController do

  # This should return the minimal set of attributes required to create a valid
  # YesOrNoTest. As you add validations to YesOrNoTest, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { {  } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # YesOrNoTestsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all yes_or_no_tests as @yes_or_no_tests" do
      yes_or_no_test = YesOrNoTest.create! valid_attributes
      get :index, {}, valid_session
      assigns(:yes_or_no_tests).should eq([yes_or_no_test])
    end
  end

  describe "GET show" do
    it "assigns the requested yes_or_no_test as @yes_or_no_test" do
      yes_or_no_test = YesOrNoTest.create! valid_attributes
      get :show, {:id => yes_or_no_test.to_param}, valid_session
      assigns(:yes_or_no_test).should eq(yes_or_no_test)
    end
  end

  describe "GET new" do
    it "assigns a new yes_or_no_test as @yes_or_no_test" do
      get :new, {}, valid_session
      assigns(:yes_or_no_test).should be_a_new(YesOrNoTest)
    end
  end

  describe "GET edit" do
    it "assigns the requested yes_or_no_test as @yes_or_no_test" do
      yes_or_no_test = YesOrNoTest.create! valid_attributes
      get :edit, {:id => yes_or_no_test.to_param}, valid_session
      assigns(:yes_or_no_test).should eq(yes_or_no_test)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new YesOrNoTest" do
        expect {
          post :create, {:yes_or_no_test => valid_attributes}, valid_session
        }.to change(YesOrNoTest, :count).by(1)
      end

      it "assigns a newly created yes_or_no_test as @yes_or_no_test" do
        post :create, {:yes_or_no_test => valid_attributes}, valid_session
        assigns(:yes_or_no_test).should be_a(YesOrNoTest)
        assigns(:yes_or_no_test).should be_persisted
      end

      it "redirects to the created yes_or_no_test" do
        post :create, {:yes_or_no_test => valid_attributes}, valid_session
        response.should redirect_to(YesOrNoTest.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved yes_or_no_test as @yes_or_no_test" do
        # Trigger the behavior that occurs when invalid params are submitted
        YesOrNoTest.any_instance.stub(:save).and_return(false)
        post :create, {:yes_or_no_test => {  }}, valid_session
        assigns(:yes_or_no_test).should be_a_new(YesOrNoTest)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        YesOrNoTest.any_instance.stub(:save).and_return(false)
        post :create, {:yes_or_no_test => {  }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested yes_or_no_test" do
        yes_or_no_test = YesOrNoTest.create! valid_attributes
        # Assuming there are no other yes_or_no_tests in the database, this
        # specifies that the YesOrNoTest created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        YesOrNoTest.any_instance.should_receive(:update_attributes).with({ "these" => "params" })
        put :update, {:id => yes_or_no_test.to_param, :yes_or_no_test => { "these" => "params" }}, valid_session
      end

      it "assigns the requested yes_or_no_test as @yes_or_no_test" do
        yes_or_no_test = YesOrNoTest.create! valid_attributes
        put :update, {:id => yes_or_no_test.to_param, :yes_or_no_test => valid_attributes}, valid_session
        assigns(:yes_or_no_test).should eq(yes_or_no_test)
      end

      it "redirects to the yes_or_no_test" do
        yes_or_no_test = YesOrNoTest.create! valid_attributes
        put :update, {:id => yes_or_no_test.to_param, :yes_or_no_test => valid_attributes}, valid_session
        response.should redirect_to(yes_or_no_test)
      end
    end

    describe "with invalid params" do
      it "assigns the yes_or_no_test as @yes_or_no_test" do
        yes_or_no_test = YesOrNoTest.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        YesOrNoTest.any_instance.stub(:save).and_return(false)
        put :update, {:id => yes_or_no_test.to_param, :yes_or_no_test => {  }}, valid_session
        assigns(:yes_or_no_test).should eq(yes_or_no_test)
      end

      it "re-renders the 'edit' template" do
        yes_or_no_test = YesOrNoTest.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        YesOrNoTest.any_instance.stub(:save).and_return(false)
        put :update, {:id => yes_or_no_test.to_param, :yes_or_no_test => {  }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested yes_or_no_test" do
      yes_or_no_test = YesOrNoTest.create! valid_attributes
      expect {
        delete :destroy, {:id => yes_or_no_test.to_param}, valid_session
      }.to change(YesOrNoTest, :count).by(-1)
    end

    it "redirects to the yes_or_no_tests list" do
      yes_or_no_test = YesOrNoTest.create! valid_attributes
      delete :destroy, {:id => yes_or_no_test.to_param}, valid_session
      response.should redirect_to(yes_or_no_tests_url)
    end
  end

end
